version: '3'

volumes:
  db-data:
    external: true

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../app/src:/app/src
    ports:
      - 8080:8080
    links:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_articles

  db:
    image: postgres
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_articles

  # agent:
  #   build:
  #     context: ../ansible
  #   links:
  #     - db
  #   environment:
  #     SERVICE_HOST: db
  #     SERVICE_PORT: 5432