version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    image: chicocode/ci-nodejs-docker
    ports:
      - 8081:8080
    links:
      - db
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_articles

  db:
    image: postgres
    hostname: db
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_articles