version: '3'

volumes:
  jenkins:
    external: true

services:
  jenkins:
    build:
      context: .
    restart: on-failure
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"