---
env:
  es6: true
  node: true
  jest: true
extends: 
  - 'eslint:recommended'
plugins:
  - 'prettier'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  prettier/prettier: 
    - error
    - singleQuote: true
      trailingComma: none
      bracketSpacing: true
      semi: false
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never