version: '3.3'

services:
  app:
    image: chicocode/articles_app
    ports:
      - 8090:8080
    links:
      - db
    deploy:
      replicas: 2
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_articles
    networks:
      - appnet

  db:
    image: postgres
    hostname: db
    deploy:
      replicas: 1
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_articles
    networks:
      - appnet

networks:
  appnet:
    driver: overlay
    attachable: true
